<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\PackageRequest;
use Illuminate\Http\Request;
use App\Repositories\PackageRepository;


class PackageController extends Controller
{
    /**
     * @OA\Get(
     *      path="/api/package",
     *      tags={"Package"},
     *      summary="Get All Package",
     *      description="Get all package",
     *      @OA\Parameter(
     *          name="limit",
     *          required=false,
     *          description="default 10",
     *          in="query",
     *          @OA\Schema(
     *              type="integer"
     *          )
     *     ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function index()
    {
        return PackageRepository::getData();
    }

    /**
     * @OA\Post(
     *      path="/api/package",
     *      tags={"Package"},
     *      summary="Create New Transaction",
     *      description="Store transaction data",
     *      @OA\RequestBody(
     *          required=true,
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(
     *                  @OA\Property(
     *                      property="customer_name",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="customer_code",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_amount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_discount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_additional_field",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_payment_type",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_state_id",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="organization_id",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_cash_amount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_cash_change",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="actual_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="volume_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="chargable_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="sla_day",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="source_tariff_db",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="id_source_tariff",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="location_code",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="pod",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="history",
     *                      type="array",
     *                      @OA\Items(
     *                          type="string"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="custom_field",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="connote_number",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="customer_attribute",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="nama_sales",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="top",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="jenis_pelanggan",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="origin_data",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="customer_name",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_email",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_phone",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address_detail",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_zip_code",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="zone_code",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="destination_data",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="customer_name",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_email",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_phone",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address_detail",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_zip_code",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="zone_code",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *              )
     *          )
     *      ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function storeTransaction(Request $request)
    {
        return PackageRepository::saveTransaction();
    }

    /**
     * @OA\Put(
     *      path="/api/package/{id}",
     *      tags={"Package"},
     *      summary="Update Transaction Package",
     *      description="Store transaction data",
     *      @OA\Parameter(
     *          name="id",
     *          description="Transaction ID",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="string"
     *          )
     *      ),
     *      @OA\RequestBody(
     *          required=true,
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(
     *                  @OA\Property(
     *                      property="customer_name",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="customer_code",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_amount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_discount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_additional_field",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_payment_type",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_state_id",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="organization_id",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_cash_amount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_cash_change",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="actual_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="volume_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="chargable_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="sla_day",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="source_tariff_db",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="id_source_tariff",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="location_code",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="pod",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="history",
     *                      type="array",
     *                      @OA\Items(
     *                          type="string"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="custom_field",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="connote_number",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="customer_attribute",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="nama_sales",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="top",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="jenis_pelanggan",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="origin_data",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="customer_name",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_email",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_phone",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address_detail",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_zip_code",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="zone_code",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="destination_data",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="customer_name",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_email",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_phone",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address_detail",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_zip_code",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="zone_code",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *              )
     *          )
     *      ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function updateTransaction(Request $request, $id)
    {
        return PackageRepository::updateTransaction($id);
    }

    /**
     * @OA\Post(
     *      path="/api/package/koli/{id}",
     *      tags={"Package"},
     *      summary="Add Koli Detail",
     *      description="Store koli data",
     *      @OA\Parameter(
     *          name="id",
     *          description="Transaction ID",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="string"
     *          )
     *      ),
     *      @OA\RequestBody(
     *          required=true,
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(
     *                  @OA\Property(
     *                      property="koli_length",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="awb_url",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_chargable_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_width",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_surcharge",
     *                      type="array",
     *                      @OA\Items(
     *                          type="string"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="koli_height",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_description",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_formula_id",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_volume",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_custom_field",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="awb_sicepat",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="harga_barang",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *              )
     *          )
     *      ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function storeKoli(Request $request, $id)
    {
        return PackageRepository::saveKoli($id);
    }

    /**
     * @OA\Put(
     *      path="/api/package/koli/{id}",
     *      tags={"Package"},
     *      summary="Update Koli Detail",
     *      description="Update koli data",
     *      @OA\Parameter(
     *          name="id",
     *          description="Koli ID",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="string"
     *          )
     *      ),
     *      @OA\RequestBody(
     *          required=true,
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(
     *                  @OA\Property(
     *                      property="koli_length",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="awb_url",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_chargable_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_width",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_surcharge",
     *                      type="array",
     *                      @OA\Items(
     *                          type="string"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="koli_height",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_description",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_formula_id",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_volume",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="koli_custom_field",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="awb_sicepat",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="harga_barang",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *              )
     *          )
     *      ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function updateKoli(Request $request, $id)
    {
        return PackageRepository::updateKoli($id);
    }

    /**
     * @OA\Get(
     *      path="/api/package/{id}",
     *      tags={"Package"},
     *      summary="Show Package Detail",
     *      description="Get package detail",
     *      @OA\Parameter(
     *          name="id",
     *          description="Transaction ID",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="string"
     *          )
     *      ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function show($id)
    {
        return PackageRepository::getDetail($id);
    }

    /**
     * @OA\Delete(
     *      path="/api/package/{id}",
     *      tags={"Package"},
     *      summary="Delete Package",
     *      description="Delete package",
     *      @OA\Parameter(
     *          name="id",
     *          description="Transaction ID",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="string"
     *          )
     *      ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function destroy($id)
    {
        return PackageRepository::destroy($id);
    }

    /**
     * @OA\Patch(
     *      path="/api/package/{id}",
     *      tags={"Package"},
     *      summary="Update Transaction Package",
     *      description="Store transaction data",
     *      @OA\Parameter(
     *          name="id",
     *          description="Transaction ID",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="string"
     *          )
     *      ),
     *      @OA\RequestBody(
     *          required=true,
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(
     *                  @OA\Property(
     *                      property="customer_name",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="customer_code",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_amount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_discount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_additional_field",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_payment_type",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_state_id",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="organization_id",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_cash_amount",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="transaction_cash_change",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="actual_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="volume_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="chargable_weight",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="sla_day",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="source_tariff_db",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="id_source_tariff",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="location_code",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="pod",
     *                      type="string"
     *                  ),
     *                  @OA\Property(
     *                      property="history",
     *                      type="array",
     *                      @OA\Items(
     *                          type="string"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="custom_field",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object"
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="connote_number",
     *                      type="integer"
     *                  ),
     *                  @OA\Property(
     *                      property="customer_attribute",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="nama_sales",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="top",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="jenis_pelanggan",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="origin_data",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="customer_name",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_email",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_phone",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address_detail",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_zip_code",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="zone_code",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *                  @OA\Property(
     *                      property="destination_data",
     *                      type="array",
     *                      @OA\Items(
     *                          type="object",
     *                          @OA\Property(
     *                              property="customer_name",
     *                              type="string",
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_email",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_phone",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_address_detail",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="customer_zip_code",
     *                              type="string"
     *                          ),
     *                          @OA\Property(
     *                              property="zone_code",
     *                              type="string"
     *                          )
     *                      )
     *                  ),
     *              )
     *          )
     *      ),
     *      @OA\Response(
     *          response="200",
     *          description="success"
     *      )
     * )
     */
    public function updatePayment(Request $request, $id)
    {
        return PackageRepository::updatePaymentStatus($id);
    }
}
